//AUTH
export const LOGIN = "LOGIN";
export const LOGIN_RED = "LOGIN_RED";
export const LOGOUT = "LOGOUT";
export const LOGOUT_RED = "LOGOUT_RED";
export const SIGNUP = "SIGNUP";
export const SIGNUP_RED = "SIGNUP_RED";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_RED = "VERIFY_EMAIL_RED";
export const VERIFY_PHONE = "VERIFY_PHONE";
export const VERIFY_PHONE_RED = "VERIFY_PHONE_RED";
export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_RED = "RESEND_EMAIL_RED";
export const RESEND_OTP = "RESEND_OTP";
export const RESEND_OTP_RED = "RESEND_OTP_RED";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_RED = "FORGOT_PASSWORD_RED";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_RED = "RESET_PASSWORD_RED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_RED = "CHANGE_PASSWORD_RED";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_RED = "REFRESH_TOKEN_RED";
export const LOGOUT_ALL_DEVICES = "LOGOUT_ALL_DEVICES";
export const LOGOUT_ALL_DEVICES_RED = "LOGOUT_ALL_DEVICES_RED";
export const DASHBOARD_ACCESS = "DASHBOARD_ACCESS";
export const DASHBOARD_ACCESS_RED = "DASHBOARD_ACCESS_RED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_AUTH = "CLEAR_AUTH";

//USER
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_RED = "CREATE_USER_RED";
export const GET_USER = "GET_USER";
export const GET_USER_RED = "GET_USER_RED";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_RED = "GET_USER_DETAILS_RED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_RED = "UPDATE_USER_RED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RED = "DELETE_USER_RED";

//VENDOR CATEGORY
export const CREATE_VENDOR_CATEGORY = "CREATE_VENDOR_CATEGORY";
export const CREATE_VENDOR_CATEGORY_RED = "CREATE_VENDOR_CATEGORY_RED";
export const GET_VENDOR_CATEGORY = "GET_VENDOR_CATEGORY";
export const GET_VENDOR_CATEGORY_RED = "GET_VENDOR_CATEGORY_RED";
export const GET_VENDOR_CATEGORY_DETAILS = "GET_VENDOR_CATEGORY_DETAILS";
export const GET_VENDOR_CATEGORY_DETAILS_RED = "GET_VENDOR_CATEGORY_DETAILS_RED";
export const UPDATE_VENDOR_CATEGORY = "UPDATE_VENDOR_CATEGORY";
export const UPDATE_VENDOR_CATEGORY_RED = "UPDATE_VENDOR_CATEGORY_RED";
export const ACTIVATE_VENDOR_CATEGORY = "ACTIVATE_VENDOR_CATEGORY";
export const ACTIVATE_VENDOR_CATEGORY_RED = "ACTIVATE_VENDOR_CATEGORY_RED";
export const DEACTIVATE_VENDOR_CATEGORY = "DEACTIVATE_VENDOR_CATEGORY";
export const DEACTIVATE_VENDOR_CATEGORY_RED = "DEACTIVATE_VENDOR_CATEGORY_RED";

//VENUE CATEGORY
export const CREATE_VENUE_CATEGORY = "CREATE_VENUE_CATEGORY";
export const CREATE_VENUE_CATEGORY_RED = "CREATE_VENUE_CATEGORY_RED";
export const GET_VENUE_CATEGORY = "GET_VENUE_CATEGORY";
export const GET_VENUE_CATEGORY_RED = "GET_VENUE_CATEGORY_RED";
export const GET_VENUE_CATEGORY_DETAILS = "GET_VENUE_CATEGORY_DETAILS";
export const GET_VENUE_CATEGORY_DETAILS_RED = "GET_VENUE_CATEGORY_DETAILS_RED";
export const UPDATE_VENUE_CATEGORY = "UPDATE_VENUE_CATEGORY";
export const UPDATE_VENUE_CATEGORY_RED = "UPDATE_VENUE_CATEGORY_RED";
export const ACTIVATE_VENUE_CATEGORY = "ACTIVATE_VENUE_CATEGORY";
export const ACTIVATE_VENUE_CATEGORY_RED = "ACTIVATE_VENUE_CATEGORY_RED";
export const DEACTIVATE_VENUE_CATEGORY = "DEACTIVATE_VENUE_CATEGORY";
export const DEACTIVATE_VENUE_CATEGORY_RED = "DEACTIVATE_VENUE_CATEGORY_RED";

//VENDOR
export const CREATE_VENDOR = "CREATE_VENDOR";
export const CREATE_VENDOR_RED = "CREATE_VENDOR_RED";
export const GET_VENDOR = "GET_VENDOR";
export const GET_VENDOR_RED = "GET_VENDOR_RED";
export const GET_VENDOR_DETAILS = "GET_VENDOR_DETAILS";
export const GET_VENDOR_DETAILS_RED = "GET_VENDOR_DETAILS_RED";
export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const UPDATE_VENDOR_RED = "UPDATE_VENDOR_RED";

//VENUE
export const CREATE_VENUE = "CREATE_VENUE";
export const CREATE_VENUE_RED = "CREATE_VENUE_RED";
export const GET_VENUE = "GET_VENUE";
export const GET_VENUE_RED = "GET_VENUE_RED";
export const GET_VENUE_DETAILS = "GET_VENUE_DETAILS";
export const GET_VENUE_DETAILS_RED = "GET_VENUE_DETAILS_RED";
export const UPDATE_VENUE = "UPDATE_VENUE";
export const UPDATE_VENUE_RED = "UPDATE_VENUE_RED";

//VENUE IMAGE
export const GET_VENUE_IMAGES = "GET_VENUE_IMAGES";
export const GET_VENUE_IMAGES_RED = "GET_VENUE_IMAGES_RED";
export const CREATE_VENUE_IMAGE = "CREATE_VENUE_IMAGE";
export const CREATE_VENUE_IMAGE_RED = "CREATE_VENUE_IMAGE_RED";
export const DELETE_VENUE_IMAGE = "DELETE_VENUE_IMAGE";
export const DELETE_VENUE_IMAGE_RED = "DELETE_VENUE_IMAGE_RED";
export const PRIMARY_VENUE_IMAGE = "PRIMARY_VENUE_IMAGE";
export const PRIMARY_VENUE_IMAGE_RED = "PRIMARY_VENUE_IMAGE_RED";
export const REORDER_VENUE_IMAGE = "REORDER_VENUE_IMAGE";
export const REORDER_VENUE_IMAGE_RED = "REORDER_VENUE_IMAGE_RED";

//PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_RED = "GET_PROFILE_RED";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const CREATE_PROFILE_RED = "CREATE_PROFILE_RED";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_RED = "UPDATE_PROFILE_RED";

//COMMON API
export const API_ERROR = "API_ERROR";
export const CLEAR_API_ERROR = "CLEAR_API_ERROR";
